version: '3.1'
services:
    backend-dev:
        container_name: backend-dev
        image: ghcr.io/eventmod/eventmod-backend:dev
        ports:
            - "3001:3000"
        environment:
            - MYSQL_DATABASE=eventmod
            - MYSQL_USER=Eventmod
            - MYSQL_PASSWORD=eventadmin
        volumes:
            - /home/eventmodadmin/backend/public:/tmp

networks:
    default:
        external:
            name: eventmod-network
