version: '3'
services:
    backend:
        container_name: backend
        build: .
        image: backend:latest
        volumes:
            - /home/eventmod/Back-End/public:/tmp
        ports:
            - "3000:3000"
        restart: always

networks:
    default :
        external:
            eventmod-network