version: '3.1'
services:
    backend:
        container_name: backend-prd
        image: ghcr.io/chicky0/eventmod-backend:prd
        ports:
            - "3000:3000"
        environment:
            - MYSQL_DATABASE=eventmod
            - MYSQL_USER=Eventmod
            - MYSQL_PASSWORD=eventadmin
        volumes:
            - /home/eventmodadmin/backend/public:/tmp

networks:
    default:
        external:
            name: eventmod-network