version: '1'
services:
    backend:
        container_name: backend
        build: .
        image: ghcr.io/chicky0/eventmod-backend:latest
        volumes:
            - /home/eventmod/Back-End/public:/tmp
        ports:
            - "3000:3000"
        restart: always

networks:
    default :
        eventmod-network:
            external: true