version: '3.1'
services:
    backend:
        image: ghcr.io/chicky0/eventmod-backend:latest
        container_name: backend
        build: .
        ports:
            - "3000:3000"
        environment:
            - MYSQL_DATABASE=eventmod
            - MYSQL_ROOT_PASSWORD=eventadmin
            - MYSQL_USER=Eventmod
            - MYSQL_PASSWORD=eventadmin
            SPRING_DATASOURCE_URL: jdbc:mysql://eventmoddb:3306/eventmod?autoReconnect=true&useSSL=false
        volumes:
            - /home/eventmodadmin/Back-End/public:/tmp
        restart: always

networks:
    default:
        external:
            name: eventmod-network