version: '3.1'
services:
    backend:
        image: ghcr.io/chicky0/eventmod-backend:latest
        container_name: backend
        build: .
        ports:
            - "3000:3000"
        environment:
            - MYSQL_DATABASE=eventmod
            - MYSQL_USER=Eventmod
            - MYSQL_PASSWORD=eventadmin
        volumes:
            - /home/eventmodadmin/Back-End/public:/tmp

networks:
    default:
        external:
            name: eventmod-network