version: '3'
services:
    backend:
        image: backend:latest
        container_name: backend
        build: .
        ports:
            - "3000:3000"
        environment:
            - MYSQL_DATABASE=eventmod
            - MYSQL_USER=Eventmod
            - MYSQL_ROOT_PASSWORD=eventadmin
        volumes:
            - /home/eventmodadmin/Back-End/public:/tmp
        networks:
            eventmod-network:
                ipv4_address: 172.20.0.5
        restart: always

networks:
    default:
        external:
            name: eventmod-network
    eventmod-network:
        external: true