version: '1'
services:
    backend:
        container_name: backend
        build: .
        image: ghcr.io/chicky0/eventmod-backend:latest
        volumes:
            - /home/eventmod/Back-End/public:/tmp
        ports:
            - "3000:3000"
        environment:
            - MYSQL_DATABASE=eventmod
            - MYSQL_USER=Eventmod
            - MYSQL_ROOT_PASSWORD=eventadmin
         volumes:
            - /home/eventmodadmin/Back-End/public:/tmp
        restart: always
        network:
            - eventmod-network

networks:
    eventmod-network:
        external: true