name: deploy-backend-prd-eventmod
on:
  push:
    branches:
      - master
  issues:
    types: opened
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.USER }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/eventmod/eventmod-backend:prd
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: pull images and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd backend-prd/
            git pull origin master
            sudo docker rm -f backend
            sudo docker rmi ghcr.io/eventmod/eventmod-backend:prd
            sudo docker pull ghcr.io/eventmod/eventmod-backend:prd
            sudo docker-compose up -d