name: deploy-backend-dev-eventmod
on:
  push:
    branches:
      - dev
  issues:
    types: opened
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - run: docker build -f Dockerfile-dev . --tag ghcr.io/eventmod/eventmod-backend:dev
      - run: docker echo ${{ secrets.TOKEN }} | login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: docker push ghcr.io/eventmod/eventmod-backend:dev
  deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: pull images and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd backend/
            git pull origin dev
            docker rm -f backend-dev
            docker rmi ghcr.io/eventmod/eventmod-backend:dev
            docker pull ghcr.io/eventmod/eventmod-backend:dev
            docker-compose -f docker-compose-dev.yml up -d
  notify:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: snow-actions/line-notify@v1.0.0
        with:
          access_token: ${{ secrets.LINE_ACCESS_TOKEN }}
          message: |
            Deploy Backend Dev Success.